theme: jekyll-theme-cayman
title: Bokyeong's Resume
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Bokyeong' s Page
baseurl: "/resume" # the subpath of your site, e.g. /blog
url: "https://KangBokyeong.github.io" # the base hostname & protocol for your site
github_username: KangBokyeong

# Build settings
